// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZWYkGxccY9O_I4I-3yKcvwV_AlEeaFVg',
    appId: '1:1090839519105:web:7d9e4c5553f254df4dd280',
    messagingSenderId: '1090839519105',
    projectId: 'coffee-store-ba0b0',
    authDomain: 'coffee-store-ba0b0.firebaseapp.com',
    storageBucket: 'coffee-store-ba0b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABd6zheTIwLxzHQQO8Er-hsxhwR3uFosU',
    appId: '1:1090839519105:android:ae809db1aceaca2f4dd280',
    messagingSenderId: '1090839519105',
    projectId: 'coffee-store-ba0b0',
    storageBucket: 'coffee-store-ba0b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmKLM8lnYuNUQCpLLIIESUuR6E2RiuT3Y',
    appId: '1:1090839519105:ios:188d13bcf4c285fc4dd280',
    messagingSenderId: '1090839519105',
    projectId: 'coffee-store-ba0b0',
    storageBucket: 'coffee-store-ba0b0.appspot.com',
    iosBundleId: 'com.example.coffeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmKLM8lnYuNUQCpLLIIESUuR6E2RiuT3Y',
    appId: '1:1090839519105:ios:188d13bcf4c285fc4dd280',
    messagingSenderId: '1090839519105',
    projectId: 'coffee-store-ba0b0',
    storageBucket: 'coffee-store-ba0b0.appspot.com',
    iosBundleId: 'com.example.coffeShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZWYkGxccY9O_I4I-3yKcvwV_AlEeaFVg',
    appId: '1:1090839519105:web:8ce8c74011575c3e4dd280',
    messagingSenderId: '1090839519105',
    projectId: 'coffee-store-ba0b0',
    authDomain: 'coffee-store-ba0b0.firebaseapp.com',
    storageBucket: 'coffee-store-ba0b0.appspot.com',
  );
}
